kind: pipeline
name: default

workspace:
  base: /go
  path: src/Recon

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add git gcc libc-dev
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go build
      - go test