kind: pipeline
name: default

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add git
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go build
      - go test